In [1]:
import numpy as np

# Show NumPy version
np.__version__

'1.19.2'

In [2]:
# NumPy build configuration
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jtrezza/opt/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jtrezza/opt/miniconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jtrezza/opt/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jtrezza/opt/miniconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jtrezza/opt/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jtrezza/opt/miniconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/jtrezza/opt/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jtrezza/opt/miniconda3/include']


In [3]:
# 2
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [4]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 0])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(np.all(a))
print(np.all(b))

False
True


In [5]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 0])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(np.any(a))
print(np.any(b))

True
True


In [6]:
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))

Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


In [7]:
a = np.array([1, 7, 13, 105])
print(f"size: {a.size * a.itemsize} bytes")

size: 32 bytes


In [8]:
a = np.array(np.concatenate((np.zeros(10).tolist(), np.ones(10).tolist(), np.full(10, 5).tolist())))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
np.arange(30, 71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [10]:
np.arange(30, 71, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.random()

0.6108063760092043

In [13]:
np.random.normal(size=15)

array([-1.30041983,  0.57763382,  2.78736126,  0.52102526, -1.49794758,
       -1.16697738,  0.15196744,  0.9600933 ,  0.66751501,  1.5718215 ,
       -1.54048079,  1.64800949,  0.38216585, -0.4944176 , -2.15857452])

In [14]:
a = np.arange(15, 56)
a[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [15]:
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [16]:
# 22
a = np.arange(21)
a[(a >= 9) & (a <= 15)] *= -1
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [19]:
# 23
np.random.randint(0, 11, 5)

array([1, 4, 3, 2, 5])

In [21]:
# 24
a = np.array([2, 3, 4])
b = np.array([5, 6, 7])
np.multiply(a, b)

array([10, 18, 28])

In [26]:
# 25
a = np.arange(10, 22)
a.reshape(3, 4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
# 28 (My solution)
x = np.zeros(100, dtype=int).reshape((10, 10))
x[0] = 1
x[-1] = 1
x[np.arange(1, 9, dtype=int), np.zeros(8, dtype=int)] = 1
x[np.arange(1, 9, dtype=int), np.full((1), -1, dtype=int)] = 1
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [57]:
# 28 (w3resource's solution)
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [76]:
# 29 (My solution)
x = np.zeros((5, 5), dtype=int)
x[np.arange(0, 5), np.arange(0, 5)] = range(1, 6)
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [78]:
# 29 (w3resrources's solution)
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [83]:
#30 (My solution - wrogn)
x = np.ones((4, 4), dtype=int)
x[np.arange(0, 4), np.arange(0, 4)] = 0
x

array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [84]:
# 30 (Their solution)
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [85]:
x = np.random.random?

In [95]:
# 31
x = np.random.random((3, 3, 3))
x

array([[[0.52159899, 0.0986114 , 0.59273229],
        [0.07641327, 0.83023219, 0.08097631],
        [0.69522304, 0.73235169, 0.92100694]],

       [[0.38529718, 0.02225833, 0.82946753],
        [0.55810859, 0.19691299, 0.65517094],
        [0.7240807 , 0.47827016, 0.04401949]],

       [[0.80483594, 0.21796074, 0.79992099],
        [0.83439197, 0.91542417, 0.51251207],
        [0.44442384, 0.40242145, 0.52780325]]])

In [107]:
# 32
x = np.random.randint(1, 11, 20).reshape((4, 5))
print(f"x: {x}")
sum_all = x.sum()
sum_cols = x.sum(axis=0)
sum_rows = x.sum(axis=1)
print(f"Sum all: {sum_all}")
print(f"Sum cols: {sum_cols}")
print(f"Sum rows: {sum_rows}")

x: [[ 4  6  2  1  4]
 [10  6  7  8  5]
 [ 6  7  9  9  7]
 [ 3 10  6  3  2]]
Sum all: 115
Sum cols: [23 29 24 21 18]
Sum rows: [17 36 38 24]


In [127]:
#34
my_rand = np.random.RandomState(0)
x = my_rand.randint(1, 11, 20).reshape((4, 5))
to_sum = np.arange(1, 6)
print("x:")
print(x)
print("To sum:")
print(to_sum)
print("Sum:")
print(np.sum((x, to_sum)))

x:
[[ 6  1  4  4  8]
 [10  4  6  3  5]
 [ 8  7  9  9  2]
 [ 7  8  8  9  2]]
To sum:
[1 2 3 4 5]
Sum:
[[ 7  3  7  8 13]
 [11  6  9  7 10]
 [ 9  9 12 13  7]
 [ 8 10 11 13  7]]
