In [1]:
# Ten random numbers
import numpy as np
rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [2]:
# This
[x[3], x[7], x[2]]
# is the same as 
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [3]:
# When doing fancy indexing, the shape of the result
# will reflect the sahape of the index array
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [4]:
# It also works on multiple dimensions
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [6]:
row[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [7]:
X[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [8]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
X[2, [2, 0, 1]]

array([10,  8,  9])

In [10]:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])