In [16]:
import numpy as np
np.random.seed(0) # Seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [23]:
print("x2 ndim: ", x3.ndim)
print("x2 shape: ", x3.shape)
print("x2 size: ", x3.size)
print("x2 dtype: ", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x2 ndim:  3
x2 shape:  (3, 4, 5)
x2 size:  60
x2 dtype:  int64
itemsize: 8 bytes
nbytes: 480 bytes


In [24]:
# Array indexing
x1

array([5, 0, 3, 3, 7, 9])

In [25]:
# Just like in python lists
x1[0]

5

In [26]:
x1[-1]

9

In [27]:
# In a multi-line array, we can access it
# using comma-separated tuples
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [28]:
x2[0, 2]

2

In [31]:
x2[2, -1]

7

In [32]:
# And they can also be modified
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [33]:
# nd arrays are of a single type
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

In [34]:
# Slice in the same way you slice a Python list x[start:stop:step]
# If any of these are unspecified, they default to the values
# start=0, stop=size of dimension, step=1
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [36]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [37]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [38]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [42]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [44]:
# Multi-dimensional slices work in the same way,
# with multiple slices separated by commas
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [45]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [46]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [47]:
x2[::-1, ::-1] # Reversed

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [55]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [58]:
# We have a copy method similar to the list's one.
# Remember that by default, np arrays' slices
# don't return copies
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[12  5]
 [ 7  6]]


In [62]:
# We can reshape a ndarray (n-dimensional array)
# It use to use a no-copy image of the array
grid = np.arange(1, 13).reshape((3, 4))
print(grid)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [64]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [65]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [66]:
# Concatenation and splitting
# np.concatenate takes a tuple or list of arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [67]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [68]:
# Two-dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [71]:
# For multidimensional arrays it's clearer
# to use .hstack and .vstack
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [72]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [74]:
# Splitting
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
# Notice that N split-points, leads to N + 1 subarrays
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [75]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [77]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
