In [6]:
import numpy as np

np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.76 s ± 7.73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
# We can just perform an operation over an array.
# These are called 'Universal Functions' (UFuncs)

# Using loops
print(compute_reciprocals(values))
# Using UFuncs
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [9]:
%timeit (1.0 / big_array)

1.81 ms ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
# We can operate over two arrays
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [12]:
# They can act on multi-dimensional arrays as well
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [14]:
# Using normal arithmetic
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x //2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x //2 = [0 0 1 1]


In [15]:
# You can use several operations combined
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [16]:
# All of these are just wrappers. e.g. the '+'
# operator is a wrapper for the 'add' function
np.add(x, 2)

array([2, 3, 4, 5])

In [17]:
theta = np.linspace(0, np.pi, 3)

In [18]:
# Trigonometric functions
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [20]:
# Specifying output
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [21]:
# We can specify the positions of the output
# in creative ways
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [22]:
# We can reduce the values
x = np.arange(1, 6)
np.add.reduce(x)

15

In [23]:
# If we want to store all the intermediate results:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [24]:
# Compute the output of all pairs of two different inputs
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])