In [1]:
# in python, we can create fixed-type arrays
import array
L = list(range(10))
# 'i' indicates the 'integer' type
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# el nd array de numpy, además de proveer almacenamiento
# eficiente de los datos en el array, provee operaciones
# eficientes usando esos datos
import numpy as np

# Formas de crear nd arrays:

# Usando Python lists
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
# La lista debe contener el mismo tipo, si no son del mismo
# tipo, numpy tratará de 'upcast' algunos datos
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
# Podemos especificar explícitamente el tipo de datos
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
# Podemos crear arrays multidimensionales usando listas
# anidadas.
# Las listas interiores son tratadas como 'rows'
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
# Podemos crear también arrays 'from Scratch', usando
# built-in methods de numpy.
# Crear un array de longitud 10, lleno de ceros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Crear un array de 3x5, tipo float, lleno de unos
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Crear uno lleno de otro valor
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 4))

array([[0.44999394, 0.37851539, 0.60020411, 0.05347078],
       [0.28785365, 0.32140897, 0.56696245, 0.92139362],
       [0.56151315, 0.75331315, 0.67788368, 0.26795838]])

In [12]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-1.06347872, -0.34272189,  0.32380466],
       [-0.39092036, -0.5181045 , -0.2002364 ],
       [ 0.40981613, -0.00779477,  0.41908765]])

In [13]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[4, 7, 7],
       [1, 4, 2],
       [3, 4, 1]])

In [14]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

In [16]:
# También podemos especificar el tipo usando un numpy
# object
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)