In [1]:
import numpy as np

# If the arrays are the same size, the operations
# are made element by element
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [2]:
# We can add a scalar to an array
a + 5

array([5, 6, 7])

In [3]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [5]:
# They're both stretched to match a common shape
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [7]:
X = np.random.random((10, 3))
X

array([[1.97803712e-01, 3.12380111e-02, 3.71224973e-01],
       [9.79975008e-01, 2.90388391e-01, 5.91849792e-01],
       [7.96737676e-01, 8.44910497e-02, 9.94382386e-01],
       [5.24339874e-01, 2.92915162e-01, 9.11904331e-06],
       [4.75138786e-01, 4.12424587e-01, 4.17696588e-02],
       [9.13571825e-01, 9.80480549e-01, 9.30799022e-01],
       [3.24077318e-01, 4.57528415e-01, 9.97343557e-01],
       [6.40279924e-01, 8.09281097e-01, 4.33086252e-01],
       [8.51325682e-02, 8.84539478e-01, 2.62963765e-02],
       [9.77921772e-01, 3.00276561e-02, 3.59303046e-01]])

In [10]:
# Mean of axis 0
Xmean = X.mean(0)
Xmean

array([0.59149785, 0.42733144, 0.47460642])